services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/library
      - JWT_SECRET=your-super-secret-key-that-is-long-and-random
      - JWT_EXPIRATION=1h
      - PORT=3000
    volumes:
      - ./backend/storage:/usr/src/app/storage
    restart: unless-stopped
    command: sh -c "npm run migration:run && npm run db:seed && npm run start:prod"

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d library"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
